title: "Pi-hole + Tailscale Homelab"
description: "Documentation complète d’un DNS sécurisé sur Raspberry Pi"
theme: minima

# Options
markdown: kramdown
highlighter: rouge

# Style
minima:
  theme: jekyll-theme-cayman

sass:
  style: compressed
